"""Structured diff stream protocol primitives."""

from .algorithm import (
    build_diff_payload,
    build_hunks,
    effective_window,
    unified_diff_text,
    validate_same_path,
    validate_window_bounds,
)
from .codec import (
    diagnostic_from_json,
    diagnostic_to_json,
    endpoint_from_json,
    endpoint_to_json,
    hunk_from_json,
    hunk_to_json,
    line_from_json,
    line_to_json,
    payload_from_json,
    payload_to_json,
    ref_from_json,
    ref_to_json,
    source_state_from_json,
    source_state_to_json,
    window_from_json,
    window_to_json,
)
from .errors import DiffStreamError, DiffStreamValidationError
from .model import (
    DIFF_CONTENT_TYPE,
    DIAGNOSTIC_CODES,
    SUPPORTED_REF_KINDS,
    DiffDiagnostic,
    DiffEndpoint,
    DiffHunk,
    DiffLine,
    DiffPayload,
    DiffRef,
    DiffSourceState,
    DiffWindow,
    format_diff_id,
    format_diff_version,
    format_hunk_id,
)

__all__ = [
    "DIFF_CONTENT_TYPE",
    "DIAGNOSTIC_CODES",
    "SUPPORTED_REF_KINDS",
    "DiffDiagnostic",
    "DiffEndpoint",
    "DiffHunk",
    "DiffLine",
    "DiffPayload",
    "DiffRef",
    "DiffSourceState",
    "DiffStreamError",
    "DiffStreamValidationError",
    "DiffWindow",
    "build_diff_payload",
    "build_hunks",
    "diagnostic_from_json",
    "diagnostic_to_json",
    "endpoint_from_json",
    "endpoint_to_json",
    "effective_window",
    "format_diff_id",
    "format_diff_version",
    "format_hunk_id",
    "hunk_from_json",
    "hunk_to_json",
    "line_from_json",
    "line_to_json",
    "payload_from_json",
    "payload_to_json",
    "ref_from_json",
    "ref_to_json",
    "source_state_from_json",
    "source_state_to_json",
    "unified_diff_text",
    "validate_same_path",
    "validate_window_bounds",
    "window_from_json",
    "window_to_json",
]
